title: pq60.info
description: The official website for the PocketQube60 standard
theme: just-the-docs

url: https://pq60.info

logo: "/assets/images/pq60_stand.svg"
favicon_ico: "/assets/images/favicon.ico"

aux_links:
  GU Orbit Main Website: https://www.guorbit.com/

footer_content: "Copyright &copy; 2014-2026 The PQ60 Working Group."
